# SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

services:
  api:
    build:
      context: ..
      dockerfile: infra/docker/api.Dockerfile
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    env_file:
      - ../apps/api/.env
    environment:
      - DEBUG=true
      - NVIDIA_API_KEY=${NVIDIA_API_KEY}
      - STORAGE_BACKEND=local
      - UPLOAD_DIR=/app/uploads
      - TEMPLATES_DIR=/app/templates
      - NUMBA_CACHE_DIR=/tmp/numba_cache
      - NUMBA_DISABLE_CACHING=1
    volumes:
      - ../apps/api:/app:delegated
      - ../apps/api/.env:/app/.env:delegated
    command: ["uvicorn", "ambient_scribe.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/app"]
    networks:
      - ambient-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/health/', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  ui:
    build:
      context: ..
      dockerfile: infra/docker/ui.dev.Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ../apps/ui/.env
    environment:
      - VITE_API_BASE=/api
      - VITE_API_PROXY_TARGET=http://api:8000
    volumes:
      - ../apps/ui:/app:delegated
      - ../apps/ui/.env:/app/.env:delegated
      - /app/node_modules
    depends_on:
      - api
    networks:
      - ambient-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

  # NVIDIA Parakeet NIM for local Riva ASR
  # Use profile 'riva-nim' to deploy: docker-compose --profile riva-nim up
  parakeet-nim:
    image: nvcr.io/nim/nvidia/parakeet-1-1b-ctc-en-us:latest
    container_name: parakeet-1-1b-ctc-en-us
    profiles:
      - riva-nim
    runtime: nvidia
    environment:
      - NGC_API_KEY=${NGC_API_KEY}
      - NIM_HTTP_API_PORT=9000
      - NIM_GRPC_API_PORT=50051
      - NIM_TAGS_SELECTOR=name=parakeet-1-1b-ctc-en-us,mode=all,vad=silero,diarizer=sortformer
    ports:
      - "9000:9000"
      - "50051:50051"
    shm_size: 8gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    networks:
      - ambient-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  # NVIDIA LLM NIM for self-hosted Llama-3.3-Nemotron-Super-49B
  # Use profile 'riva-nim' to deploy: docker-compose --profile riva-nim up
  llama-nim:
    image: nvcr.io/nim/nvidia/llama-3.3-nemotron-super-49b-v1:latest
    container_name: llama-3.3-nemotron-super-49b-v1
    profiles:
      - riva-nim
    runtime: nvidia
    ports:
      - "8001:8000"
    shm_size: 16gb
    volumes:
      - nim-llm-cache:/opt/nim/.cache
    environment:
      - NIM_CACHE_PATH=/opt/nim/.cache
      - NGC_API_KEY=${NGC_API_KEY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['all']
              capabilities: [gpu]
    networks:
      - ambient-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/health"]
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 1800s

networks:
  ambient-network:
    driver: bridge

volumes:
  nim-llm-cache:
    driver: local